In [2]:
import pandas as pd
import numpy as np
import csv
import os
import sys

In [4]:
df = pd.read_csv("data/archive/mds_V2_5.372k.csv")

In [5]:
df.head()

,Unnamed: 0.1,Unnamed: 0,apartment_id,site_id,building_id,plan_id,floor_id,unit_id,area_id,unit_usage,entity_type,entity_subtype,geom,elevation,height,zoning,roomtype
0,0,0,3c3b1d6ca8b4b9092480b8c75f9eaa81,210,399,1054,1588,7300.0,619311.0,RESIDENTIAL,area,BATHROOM,POLYGON ((-2.7337844078265210 4.07980744083215...,0.0,2.6,Zone3,Bathroom
1,1,1,3c3b1d6ca8b4b9092480b8c75f9eaa81,210,399,1054,1588,7300.0,619303.0,RESIDENTIAL,area,LIVING_ROOM,POLYGON ((5.8278988701887320 7.816876723402971...,0.0,2.6,Zone2,Livingroom
2,2,2,3c3b1d6ca8b4b9092480b8c75f9eaa81,210,399,1054,1588,7300.0,619322.0,RESIDENTIAL,area,ROOM,POLYGON ((6.7557107205191187 2.413369594812586...,0.0,2.6,Zone1,Bedroom
3,3,3,3c3b1d6ca8b4b9092480b8c75f9eaa81,210,399,1054,1588,7300.0,619310.0,RESIDENTIAL,area,KITCHEN,POLYGON ((3.5821200013910017 5.140461688341117...,0.0,2.6,Zone2,Kitchen
4,4,4,3c3b1d6ca8b4b9092480b8c75f9eaa81,210,399,1054,1588,7300.0,619312.0,RESIDENTIAL,area,ROOM,POLYGON ((3.0141380455489282 4.182056855151666...,0.0,2.6,Zone1,Bedroom

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1086846 entries, 0 to 1086845
Data columns (total 17 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   Unnamed: 0.1    1086846 non-null  int64
 1   Unnamed: 0      1086846 non-null  int64
 2   apartment_id    893479 non-null   str
 3   site_id         1086846 non-null  int64
 4   building_id     1086846 non-null  int64
 5   plan_id         1086846 non-null  int64
 6   floor_id        1086846 non-null  int64
 7   unit_id         893479 non-null   float64
 8   area_id         203330 non-null   float64
 9   unit_usage      1086846 non-null  str
 10  entity_type     1086846 non-null  str
 11  entity_subtype  1086846 non-null  str
 12  geom            1086846 non-null  str
 13  elevation       1086846 non-null  float64
 14  height          1086846 non-null  float64
 15  zoning          1086846 non-null  str
 16  roomtype        1086846 non-null  str
dtypes: float64(4), int64(6), str(7)
memory usage: 141.0 MB

,Unnamed: 0.1,Unnamed: 0,site_id,building_id,plan_id,floor_id,unit_id,area_id,elevation,height
count,1.086846e+06,1.086846e+06,1.086846e+06,1.086846e+06,1.086846e+06,1.086846e+06,893479.000000,2.033300e+05,1.086846e+06,1.086846e+06
mean,5.941842e+05,5.941842e+05,2.129186e+03,3.669807e+03,1.135549e+04,1.541823e+04,63095.770409,7.232496e+05,5.503359e+00,2.434180e+00
std,3.399705e+05,3.399705e+05,3.281492e+03,5.014763e+03,1.337158e+04,1.538432e+04,46062.368016,4.240966e+05,6.083150e+00,2.808077e-01
min,0.000000e+00,0.000000e+00,1.700000e+01,1.000000e+00,2.000000e+00,2.300000e+01,4967.000000,2.737210e+05,-2.900000e+00,5.500000e-01
25%,2.986762e+05,2.986762e+05,4.080000e+02,1.055000e+03,3.116000e+03,4.840000e+03,26770.000000,3.941622e+05,5.000000e-01,2.000000e+00
50%,6.038985e+05,6.038985e+05,8.270000e+02,1.888000e+03,5.889000e+03,9.669000e+03,51760.000000,5.880095e+05,2.900000e+00,2.600000e+00
75%,8.888238e+05,8.888238e+05,1.939000e+03,3.156000e+03,9.573000e+03,1.543100e+04,95004.000000,9.425328e+05,8.700000e+00,2.600000e+00
max,1.175256e+06,1.175256e+06,1.192300e+04,1.865500e+04,4.439400e+04,5.172300e+04,161624.000000,1.680629e+06,5.774000e+01,3.130000e+00